### ISSUE TITLE
Intermittent CUDA Out of Memory Errors during Parakeet-TDT-0.6B Fine-tuning

### ISSUE THREAD

**Issue by dapeng1345** [NVIDIA-NeMo/NeMo#15037]
# Intermittent CUDA Out of Memory Errors during Parakeet-TDT-0.6B Fine-tuning

## Describe the bug

Intermittent and unpredictable CUDA out-of-memory errors occur during fine-tuning of the Parakeet-TDT-0.6B model. The error happens randomly during training epochs and is not consistently reproducible across different runs.

## Steps/Code to reproduce bug

**Minimal reproduction steps:**

1. Use the NVIDIA PyTorch container:

2. Run fine-tuning with the following command:
python ./NeMo/examples/asr/speech_to_text_finetune.py
--config-path=/data/parakeet_finetune/
--config-name=config.yaml
+init_from_pretrained_model="nvidia/parakeet-tdt-0.6b-v3"

3. Use any audio dataset (tested with CV-Corpus-22.0-2025-06-20, ~230 hours)

**Minimal config.yaml:**

model:
train_ds:
batch_size: 4 # Tried 2, 4, 8, 16, 32
# ... other dataset configs

The error occurs randomly during training, typically after several thousand steps.

## Expected behavior

Training should proceed without intermittent out-of-memory errors, especially given that substantial GPU memory (50+ GB) is available when the crashes occur.

## Environment overview

- Environment location: Bare-metal and Docker
- Method of NeMo install: From source (NeMo examples repository)
- Docker commands:

docker pull [nvcr.io/nvidia/pytorch:25.09-py3](https://nvcr.io/nvidia/pytorch:25.09-py3)

## Environment details

Since using NVIDIA docker image, the environment includes:
- OS: Likely Ubuntu (from NVIDIA container)
- PyTorch version: Included in nvcr.io/nvidia/pytorch:25.09-py3
- Python version: 3.12

## Additional context

GPU Models Tested:
- RTX 4090 24GB
- RTX 4090 48GB  
- DGX with 128GB VRAM

Error Characteristics:
- Error occurs at nemo/collections/asr/losses/rnnt.py, line 467 in forward()
- Attempts to allocate extremely large memory (56+ GB) despite having free memory
- Error happens during log_probs.float() conversion
- Intermittent - not reproducible with consistent pattern

Memory State at Crash:
GPU total capacity: 119.70 GiB
Free memory: 50.79 GiB
Process memory usage: 52.42 GiB
PyTorch allocated: 51.22 GiB

Attempted Mitigations:
- Various batch sizes (2, 4, 8, 16, 32)
- PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
- Different hardware configurations

Suspected Issues:
1. Memory fragmentation in RNN-T loss computation
2. Peak memory usage spikes with certain audio samples
3. Possible memory leak in transducer loss calculation

The intermittent nature suggests this may be related to specific data samples or dynamic computational graph characteristics rather than consistent memory overflows.

**Comment by EivindRebnord** [comment]
+1 on this. I have experienced the same on my Windows desktop with RTX5090 (several batch sizes tried). Trained for several thousand steps, then towards the end of the epoch it/s was drastically reduced until it crashed. Experienced the same multiple times both on Windows and WSL2

**Comment by jeremy110** [comment]
Which version of nemo are you using for the training? I've tested 2.4.0 and it's fine. Also, there can be issues with CUDA Out of Memory. If you're using the native version of nemo and batch size is involved, it might be related to long audio files or very long text. The latter can lead to OOM during loss calculation. Additionally, if you use change_vocabulary, it is recommended to modify it as follows to ensure proper use of TDT.  
Another recommendation is to use Lhotse.

<img width="1664" height="642" alt="Image" src="https://github.com/user-attachments/assets/5493787d-0eb1-4772-95cb-3711e042e90a" />

**Comment by dapeng1345** [comment]
Name: nemo-toolkit                                                                                                       
Version: 2.5.2                                                                                                           
Summary: NeMo - a toolkit for Conversational AI                                                                          
Home-page: https://github.com/nvidia/nemo

**Comment by dapeng1345** [comment]
python ./NeMo/examples/asr/speech_to_text_finetune.py   --config-path=/data/parakeet_finetune/   --config-name=config.yaml   +init_from_pretrained_model="nvidia/parakeet-tdt-0.6b-v3"

config.yaml
`name: &name FastConformer-Hybrid-TDT-CTC-BPE

trainer:
  num_nodes: 1
  accelerator: gpu
  devices: 1
  max_epochs: 5
  max_steps: -1
  val_check_interval: 0.1
  precision: bf16-mixed
  gradient_clip_val: 1.0  # 启用梯度裁剪，避免梯度爆炸
  benchmark: false
  enable_checkpointing: false  # exp_manager处理
  logger: false  # exp_manager处理
  log_every_n_steps: 200
  check_val_every_n_epoch: 1

exp_manager:
  exp_dir: /data/parakeet_finetune/checkpoints
  name: parakeet_finetune_italian
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  use_datetime_version: false
  version: test
  resume_if_exists: true
  resume_ignore_no_checkpoint: true
  # 添加检查点回调参数，监控val_wer而不是val_loss
  checkpoint_callback_params:
    monitor: "val_wer"  # 监控词错误率
    mode: "min"         # WER越低越好
    save_top_k: 3       # 保存最好的3个检查点
    save_last: true     # 同时保存最后一个检查点
    every_n_epochs: 1   # 每个epoch都检查

model:
  sample_rate: 16000
  torch_float32_matmul_precision: medium
  # 冻结策略 - 专注于意大利语特性
  freeze_encoder: false    # 解冻encoder学习意大利语声学特征
  freeze_decoder: false    # 解冻decoder适应意大利语语言模型
  freeze_joint: true       # 冻结joint保持多语言对齐能力
  
  # 训练数据集配置
  train_ds:
    manifest_filepath: /data/parakeet_finetune/data/italian/train_manifest.json
    sample_rate: ${model.sample_rate}
    batch_size: 16  # 稍微增加batch_size，解冻后可能需要更多数据
    trim_silence: true
    max_duration: 10
    min_duration: 1.0  # 添加最小时长过滤
    shuffle: true
    is_tarred: false
    tarred_audio_filepaths: null
    num_workers: 2
    pin_memory: true
    text_field: "text"  # 确保字段名正确

  # 验证数据集配置
  validation_ds:
    manifest_filepath: /data/parakeet_finetune/data/italian/val_manifest.json
    sample_rate: ${model.sample_rate}
    batch_size: 8
    shuffle: false
    num_workers: 2
    pin_memory: true
    text_field: "text"  # 确保字段名正确

  # 测试数据集配置
  test_ds:
    manifest_filepath: /data/parakeet_finetune/data/italian/test_manifest.json
    sample_rate: ${model.sample_rate}
    batch_size: 8
    shuffle: false
    num_workers: 2

  # Tokenizer配置 - 使用意大利语专用tokenizer
  tokenizer:
    dir: /data/it_tokenizer
    type: bpe

  # 预处理器配置
  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    normalize: per_feature
    window_size: 0.025
    sample_rate: ${model.sample_rate}
    window_stride: 0.01
    window: hann
    features: 80
    n_fft: 512
    frame_splicing: 1
    dither: 0.00001
    stft_conv: false

  # 数据增强
  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    freq_masks: 2
    time_masks: 10
    freq_width: 27
    time_width: 0.05

  # Encoder配置
  encoder:
    _target_: nemo.collections.asr.modules.ConformerEncoder
    feat_in: ${model.preprocessor.features}
    feat_out: -1
    n_layers: 18
    d_model: 512
    subsampling: vggnet
    subsampling_factor: 4
    subsampling_conv_chunking_factor: 1
    ff_expansion_factor: 4
    self_attention_model: rel_pos_local_attn
    n_heads: 8
    att_context_size: [128, 128]
    att_context_style: regular
    xscaling: true
    untie_biases: true
    pos_bias_u_heads: 0
    pos_bias_v_heads: 0
    conv_kernel_size: 31
    conv_norm_type: batch_norm
    conv_context_size: null
    dropout: 0.1
    dropout_pre_encoder: 0.1
    dropout_emb: 0.0
    dropout_att: 0.1

  # Decoder配置
  decoder:
    _target_: nemo.collections.asr.modules.RNNTDecoder
    prednet:
      pred_hidden: 640
      pred_rnn_layers: 1
      dropout: 0.1

  # Joint网络配置
  joint:
    _target_: nemo.collections.asr.modules.TransducerJoint
    jointnet:
      joint_hidden: 640
      activation: relu
      dropout: 0.1
      num_extra_linears: 0

  # 解码策略
  decoding:
    strategy: greedy_batch
    greedy:
      max_symbols: 30
    beam:
      beam_size: 4
      return_transcription: true
      return_best_hypothesis: true
    ctc_decoding:
      strategy: greedy
      greedy:
        max_symbols_per_step: 30
    compute_timestamps: false

  # 损失函数
  loss:
    _target_: nemo.collections.asr.losses.TransducerLoss
    fused_batch_size: -1

  # 优化器配置 - 微调时使用更保守的学习率
  optim:
    name: adamw
    lr: 0.0001  # 降低学习率，避免破坏预训练权重
    betas: [0.9, 0.98]
    weight_decay: 0.001
    sched:
      name: CosineAnnealing  # 改用余弦退火，更适合微调
      warmup_steps: 1000     # 增加预热步数
      min_lr: 1e-6          # 最小学习率

  # 评估指标
  calculate_wer: true
  ctc_reduction: mean_batch
  debug: false
  max_symbol_per_sample: 300`

**Comment by anhnami** [comment]
fused_batch_size: 2

**Comment by Nightwing-77** [comment]
> # Intermittent CUDA Out of Memory Errors during Parakeet-TDT-0.6B Fine-tuning
> ## Describe the bug
> Intermittent and unpredictable CUDA out-of-memory errors occur during fine-tuning of the Parakeet-TDT-0.6B model. The error happens randomly during training epochs and is not consistently reproducible across different runs.
> 
> ## Steps/Code to reproduce bug
> **Minimal reproduction steps:**
> 
> 1. Use the NVIDIA PyTorch container:
> 2. Run fine-tuning with the following command:
>    python ./NeMo/examples/asr/speech_to_text_finetune.py
>    --config-path=/data/parakeet_finetune/
>    --config-name=config.yaml
>    +init_from_pretrained_model="nvidia/parakeet-tdt-0.6b-v3"
> 3. Use any audio dataset (tested with CV-Corpus-22.0-2025-06-20, ~230 hours)
> 
> **Minimal config.yaml:**
> 
> model: train_ds: batch_size: 4 # Tried 2, 4, 8, 16, 32
> 
> # ... other dataset configs
> The error occurs randomly during training, typically after several thousand steps.
> 
> ## Expected behavior
> Training should proceed without intermittent out-of-memory errors, especially given that substantial GPU memory (50+ GB) is available when the crashes occur.
> 
> ## Environment overview
> * Environment location: Bare-metal and Docker
> * Method of NeMo install: From source (NeMo examples repository)
> * Docker commands:
> 
> docker pull [nvcr.io/nvidia/pytorch:25.09-py3](https://nvcr.io/nvidia/pytorch:25.09-py3)
> 
> ## Environment details
> Since using NVIDIA docker image, the environment includes:
> 
> * OS: Likely Ubuntu (from NVIDIA container)
> * PyTorch version: Included in nvcr.io/nvidia/pytorch:25.09-py3
> * Python version: 3.12
> 
> ## Additional context
> GPU Models Tested:
> 
> * RTX 4090 24GB
> * RTX 4090 48GB
> * DGX with 128GB VRAM
> 
> Error Characteristics:
> 
> * Error occurs at nemo/collections/asr/losses/rnnt.py, line 467 in forward()
> * Attempts to allocate extremely large memory (56+ GB) despite having free memory
> * Error happens during log_probs.float() conversion
> * Intermittent - not reproducible with consistent pattern
> 
> Memory State at Crash: GPU total capacity: 119.70 GiB Free memory: 50.79 GiB Process memory usage: 52.42 GiB PyTorch allocated: 51.22 GiB
> 
> Attempted Mitigations:
> 
> * Various batch sizes (2, 4, 8, 16, 32)
> * PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
> * Different hardware configurations
> 
> Suspected Issues:
> 
> 1. Memory fragmentation in RNN-T loss computation
> 2. Peak memory usage spikes with certain audio samples
> 3. Possible memory leak in transducer loss calculation
> 
> The intermittent nature suggests this may be related to specific data samples or dynamic computational graph characteristics rather than consistent memory overflows.

did u guys try dynamic batching !?! i'm also facing the same issue and am considering that!! i feel it might be cause of variable audio sizes and fixed count so sometimes big audios bundle up in a batch and causes OOM

**Comment by jeremy110** [comment]
@dapeng1345 
Basically, these settings look fine. I see you set the max duration to 10 and the batch size to 16, which should be okay. May I ask if you’ve checked your data as I mentioned above?

1.You can try calculating the average and standard deviation using len of tokens / duration, and keep only the data within ±2 standard deviations.

2.You can use Lhotse to dynamically adjust the batch size (I can provide the related YAML configuration, but the prerequisite is that your data must be correct).

**Comment by jeremy110** [comment]
@dapeng1345 @Nightwing-77 
This is the setting I use for my training of 110m for 24G GPU memory, max_duration can be set to 600s, if it's 0.6b, it should be set to 200s.
```
train_ds:
    use_lhotse: True
    tarred_audio_filepaths: null
    input_cfg:
      - type: nemo
        manifest_filepath: train_hi.json
        weight: 0.7
        tags:
          lang: hi
      - type: nemo
        manifest_filepath: en_en_asr.json
        weight: 0.3
        tags:
          lang: en

    sample_rate: ${model.sample_rate}
    batch_size: null # you may increase batch_size if your memory allows
    shuffle: true
    num_workers: 4 #
    pin_memory: false
    max_duration: 30.0 #16.0
    min_duration: 1.0
    # tarred datasets
    is_tarred: false
    shuffle_n: 2048
    # bucketing params
    bucketing_strategy: "fully_randomized"
    use_bucketing: True
    num_buckets: 30
    bucket_duration_bins: null
    batch_duration: 600
    quadratic_duration: 15
    bucket_buffer_size: 20000
    shuffle_buffer_size: 10000
```

**Comment by Nightwing-77** [comment]
Hey so I had a similar setup based on trial and error and I'm facing issues related to convergence of parakeet!! Any specific reason for it!! Or it's just the lack of data for now> @dapeng1345 @Nightwing-77 
> This is the setting I use for my training of 110m for 24G GPU memory, max_duration can be set to 600s, if it's 0.6b, it should be set to 200s.
> ```
> train_ds:
>     use_lhotse: True
>     tarred_audio_filepaths: null
>     input_cfg:
>       - type: nemo
>         manifest_filepath: train_hi.json
>         weight: 0.7
>         tags:
>           lang: hi
>       - type: nemo
>         manifest_filepath: en_en_asr.json
>         weight: 0.3
>         tags:
>           lang: en
> 
>     sample_rate: ${model.sample_rate}
>     batch_size: null # you may increase batch_size if your memory allows
>     shuffle: true
>     num_workers: 4 #
>     pin_memory: false
>     max_duration: 30.0 #16.0
>     min_duration: 1.0
>     # tarred datasets
>     is_tarred: false
>     shuffle_n: 2048
>     # bucketing params
>     bucketing_strategy: "fully_randomized"
>     use_bucketing: True
>     num_buckets: 30
>     bucket_duration_bins: null
>     batch_duration: 600
>     quadratic_duration: 15
>     bucket_buffer_size: 20000
>     shuffle_buffer_size: 10000
> ```

**Comment by Nightwing-77** [comment]
Instead of fully randomized I had sorting based batching in which we had 5 classes based on size of it and created varying batch sizes based on them(I thought that might be more effective) would love to get your opinion on it > @dapeng1345 
> Basically, these settings look fine. I see you set the max duration to 10 and the batch size to 16, which should be okay. May I ask if you’ve checked your data as I mentioned above?
> 
> 1.You can try calculating the average and standard deviation using len of tokens / duration, and keep only the data within ±2 standard deviations.
> 
> 2.You can use Lhotse to dynamically adjust the batch size (I can provide the related YAML configuration, but the prerequisite is that your data must be correct).

**Comment by jeremy110** [comment]
@Nightwing-77 
Can you provide information (ex: tensorboard graph) related to "facing issues related to the convergence of parakeets"?

**Comment by dapeng1345** [comment]
@jeremy110
I used the Common Voice dataset and ran a Python script to check the audio files. All audio clips were between 1 and 15 seconds long and showed no issues. I also agreed to convert them to a 16,000 Hz sample rate.

**Comment by jeremy110** [comment]
@dapeng1345
That should have nothing to do with the data.
I took a quick look at the code. If it uses the rnnt loss, it would enter this else block. However, our goal is to use the TDT loss. Have you modified it as I mentioned above in chance_vocabulary? If not, the default is the rnnt loss, not the TDT loss.
However, it's quite peculiar that I remember using rnnt loss didn't necessarily lead to OOM.

**Comment by Nightwing-77** [comment]
@jeremy110 hey , i've been stuck in one issue on how to train nemo model on parquet files !! i added https://huggingface.co/datasets/ai4bharat/IndicVoices to my training data ! but the issue is that nemo expects audio path in manifest! but in parquet it has the all the audio nd etc inside of it !!

**Comment by jeremy110** [comment]
@Nightwing-77 Currently, Nemo does not support Parquet, so I read Parquet and then saved the aduio in a wav file and wrote it to a manifest.json file.

**Comment by Nightwing-77** [comment]
@jeremy110 hey so actually i don't have any tensorboard graphs as i switched logging off cause i was getting many issues in it (kaggle) so i trained it for around 10K steps (around 0.5 epoch ) i had like 1500 hr audios ! so the issue was i was getting output as WER predicted:<|hi|> ha~
 for all !! irrespective of what input is ! no matter what ! language,content dosen't matter ! i am only getting output as <|hi|> ha~
 ! what could be the reason for it !

**Comment by jeremy110** [comment]
@Nightwing-77 This is normal. It's only when the 10k steps are ready to start converging, and it's not until the 20k to 30k steps that the output will appear.

**Comment by Nightwing-77** [comment]
> [@Nightwing-77](https://github.com/Nightwing-77) This is normal. It's only when the 10k steps are ready to start converging, and it's not until the 20k to 30k steps that the output will appear.

is it alright till 15k steps !?! additionally should we pre include the language tag !! like in training it shoudn't predict the tag but would already know it !! i tried to make it predict the tag automally but it's causing issues as wrong prediction will cause the whole outcome to be wrong! additionally  does transliterating  a language into a unified token space like SLP1 or smth ! would it work !?!

**Comment by Nightwing-77** [comment]
@jeremy110 does nemo not support control tokens !?! cause control tokens are not meant to be predicted , or computed in rnnt loss

**Comment by jeremy110** [comment]
@Nightwing-77 @dapeng1345 
If you are interested, please refer to. https://github.com/jeremy110/Finetune_Nemo_ASR

**Comment by jeremy110** [comment]
@Nightwing-77 I haven't tried to have him predict the lang tag, not sure how to do it. I will first suggest that you train general ones first, confirm that you can train them before considering other issues.

**Comment by cnlinxi** [comment]
> Which version of nemo are you using for the training? I've tested 2.4.0 and it's fine. Also, there can be issues with CUDA Out of Memory. If you're using the native version of nemo and batch size is involved, it might be related to long audio files or very long text. The latter can lead to OOM during loss calculation. Additionally, if you use change_vocabulary, it is recommended to modify it as follows to ensure proper use of TDT. Another recommendation is to use Lhotse.
> 
> <img alt="Image" width="1664" height="642" src="https://private-user-images.githubusercontent.com/52516810/511080002-5493787d-0eb1-4772-95cb-3711e042e90a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njg5NjcwMDAsIm5iZiI6MTc2ODk2NjcwMCwicGF0aCI6Ii81MjUxNjgxMC81MTEwODAwMDItNTQ5Mzc4N2QtMGViMS00NzcyLTk1Y2ItMzcxMWUwNDJlOTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMTIxVDAzMzgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhM2UxOTJhYjk3Y2MwNTBjNjdjMGY5MmMwNmRkNjdkMGQ2MmQ4YjBhYWEyMTI0Y2U4MmQ1MWI3NzIyNzE4OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QBgU0QXNoFiXFk2QGf7MfXteO2DxvMwX-XAUKkhuGhE">

@jeremy110 
Hello, I am currently attempting to fine-tune `parakeet-tdt-v3`. What does the expression `num_classes = self.num_classes_with_blank -1 - self.joint.num_extra_outputs` in the image above mean? I have followed the instruction:

```python
asr_model.joint.joint_net[2].weight[-6:] = ori_joint_joint_net_Linear.weight[-6:]
```

> https://github.com/jeremy110/Finetune_Nemo_ASR/blob/a1e4ab2a0f521520fb61533d0a2639fd5fbbe35e/src/ft_110M_enhi_demo.py#L118C1-L118C90

Do I still need to make this modifications: `num_classes = self.num_classes_with_blank -1 - self.joint.num_extra_outputs`?

Thank you.

**Comment by jeremy110** [comment]
@cnlinxi Hi~
TDT will have five duration tokens, so you need to subtract 5 more. Also, you can directly try my GitHub above; I’ve fixed some bugs there and provided a basic script for you to run

**Comment by cnlinxi** [comment]
> Hi~ TDT will have five duration tokens, so you need to subtract 5 more. Also, you can directly try my GitHub above; I’ve fixed some bugs there and provided a basic script for you to run

@jeremy110 
Thank you for your reply. Yes, I am using your [Finetune_Nemo_ASR](https://github.com/jeremy110/Finetune_Nemo_ASR) repo above, which is really nice. I have found similar modifications in the image:
> https://github.com/jeremy110/Finetune_Nemo_ASR/blob/a1e4ab2a0f521520fb61533d0a2639fd5fbbe35e/NeMo-2.4.0/nemo/collections/asr/models/rnnt_bpe_models.py#L421

Due to some reasons, I need to use NeMo 2.6.0, so I will continue to try using your `merge_token.py`, `ft_110M_enhi_demo.py` and NeMo 2.6.0. Thank you again for your response.

**Comment by jeremy110** [comment]
@cnlinxi 
No problem. You can use NeMo v2.6, but you’ll need to modify the loss initialization. Also, there is a reinitial step in the TDT decode that needs to be changed; otherwise, the evaluation WER calculation can behave a bit strangely.

Previously, we tested v2 0.6B with merged tokens and it worked fine for English, but this doesn’t work in v3. You can try this part yourself. Hopefully this information helps you.

**Comment by cnlinxi** [comment]
@jeremy110 

Thank you, this information is very helpful to me. Regarding "the reinitialization step in the TDT decode that needs to be changed", what you said is from:

```python
if self.state is None or self.state.need_reinit(encoder_output):
    self._graph_reinitialize(encoder_output, encoder_output_length)
```

to

```python
self._graph_reinitialize(encoder_output, encoder_output_length)
```

Is that the case?

**Comment by jeremy110** [comment]
@cnlinxi 
Yes, that's right. If you use bf16 for training and don't _graph_rein initialization every time, I've found that there can be some bugs.

**Comment by cnlinxi** [comment]
@jeremy110 
Thank you very much👍
